### ISSUE TITLE
Client Timeout not working

### ISSUE THREAD

**Issue by lordrhodos** [fterrag/simple-sqsd#20]
Hej, 

we are using the daemon in a project where we define the `terrag/simple-sqsd:latest` image in docker-compose as service:

```yaml
    specter-sqsd:
        image: fterrag/simple-sqsd:latest
        container_name: specter-sqsd
        environment:
            SQSD_AWS_ENDPOINT: 'http://specter-sqs:9324'
            AWS_ACCESS_KEY_ID: 'foo'
            AWS_SECRET_ACCESS_KEY: 'bar'
            SQSD_HMAC_SECRET_KEY: 'a secret key'
            SQSD_HTTP_HMAC_HEADER: 'MAC'
            SQSD_QUEUE_REGION: 'elasticmq'
            SQSD_QUEUE_URL: 'http://specter-sqs:9324/queue/specter'
            SQSD_HTTP_URL: 'http://specter-app/messages'
            SQSD_HTTP_TIMEOUT: 20
            SQSD_HTTP_CONTENT_TYPE: 'application/json'
        networks:
            starweb:
                aliases:
                    - specter-sqsd
```

I need to change the client timout setting, but I had not luck so far and I think this is an error in the daemon. 

Even without setting `SQSD_HTTP_TIMEOUT` the messages will be resent to the url configured in `SQSD_HTTP_URL` after 10 seconds. If I set a break point in our application at the urls endpoint the messages will be sent in total for three times.

![Bildschirmfoto 2020-10-09 um 14 23 05](https://user-images.githubusercontent.com/807902/95584949-cab45c80-0a3e-11eb-8f1f-b7a7ba2df2d9.jpg)
